name: Build JABER APKs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build Release APKs
        run: ./gradlew assembleRelease

      - name: Collect APKs
        run: |
          mkdir -p Jaber-APKs
          find . -type f -name "*.apk" -exec cp {} Jaber-APKs/ \;

      - name: Upload JABER APKs
        uses: actions/upload-artifact@v4
        with:
          name: Jaber-APKs
          path: Jaber-APKs/
